# Generated by Django 5.2.1 on 2025-05-26 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='pests/')),
            ],
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_description', models.TextField()),
                ('grower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PestCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_checked', models.DateField()),
                ('part_of_plant', models.CharField(max_length=100)),
                ('num_trees_checked', models.PositiveIntegerField()),
                ('num_positive', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('farm_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mango_pests.farmblock')),
                ('pest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mango_pests.pest')),
            ],
        ),
        migrations.AddField(
            model_name='pest',
            name='plant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pests', to='mango_pests.planttype'),
        ),
    ]
