# Generated by Django 5.1.7 on 2025-05-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_pests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestcheck',
            name='num_trees',
            field=models.PositiveIntegerField(default=0, help_text='Total number of trees checked.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pestcheck',
            name='path_pattern',
            field=models.CharField(choices=[('ZigZag', 'Zig-Zag between rows'), ('Cross', 'Cross-row random sample'), ('Edge', 'Edge perimeter only')], default='ZigZag', help_text='Pick your walk pattern through the block.', max_length=20),
        ),
        migrations.AddField(
            model_name='pestcheck',
            name='positives',
            field=models.PositiveIntegerField(default=0, help_text='Number of trees with visible pest signs.'),
            preserve_default=False,
        ),
    ]
